name: "[reusable] build-pio"

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
      input-artifact:
        required: false
        type: string
      input-path:
        required: false
        type: string
        default: "artifact/"
      project-directory:
        required: false
        type: string
        default: "."
      args:
        required: false
        type: string
      pre-build:
        required: false
        type: string
      post-build:
        required: false
        type: string
      files:
        required: false
        type: string
      output-artifact:
        required: false
        type: string
        default: "platformio-build"
    outputs:
      artifact:
        value: ${{ inputs.output-artifact }}

jobs:
  build-pio:
    name: pio run
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        if: ${{ inputs.input-artifact != '' }}
        with:
          name: ${{ inputs.input-artifact }}
          path: ${{ inputs.input-path }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Run pre-build step
        if: ${{ inputs.pre-build != '' }}
        working-directory: ${{ inputs.project-directory }}
        run: ${{ inputs.pre-build }}

      - name: Build PlatformIO project
        working-directory: ${{ inputs.project-directory }}
        run: |
          pio run ${{ inputs.args }}

      - name: Run post-build step
        if: ${{ inputs.post-build != '' }}
        working-directory: ${{ inputs.project-directory }}
        run: ${{ inputs.post-build }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: ${{ inputs.files != '' }}
        with:
          name: ${{ inputs.output-artifact }}
          path: ${{ inputs.files }}
