name: "[reusable] build-poetry"

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
      input-artifact:
        required: false
        type: string
      input-path:
        required: false
        type: string
        default: "artifact/"
      python-version:
        required: false
        type: string
        default: "3.10"
      project-directory:
        required: false
        type: string
        default: "."
      args:
        required: false
        type: string
      pre-build:
        required: false
        type: string
      post-build:
        required: false
        type: string
      files:
        required: false
        type: string
      output-artifact:
        required: false
        type: string
        default: "poetry-build"
    outputs:
      artifact:
        value: ${{ inputs.output-artifact }}

jobs:
  build-poetry:
    name: poetry build
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        if: ${{ inputs.input-artifact != '' }}
        with:
          pattern: ${{ inputs.input-artifact }}
          path: ${{ inputs.input-path }}
          merge-multiple: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install poetry
        uses: Gr1N/setup-poetry@v8

      - name: Run pre-build step
        if: ${{ inputs.pre-build != '' }}
        working-directory: ${{ inputs.project-directory }}
        run: ${{ inputs.pre-build }}

      - name: Build Python package
        working-directory: ${{ inputs.project-directory }}
        run: |
          poetry build ${{ inputs.args }}

      - name: Run post-build step
        if: ${{ inputs.post-build != '' }}
        working-directory: ${{ inputs.project-directory }}
        run: ${{ inputs.post-build }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ inputs.files != '' }}
        with:
          name: ${{ inputs.output-artifact }}
          path: ${{ inputs.files }}
