name: "[reusable] gh-release"

on:
  workflow_call:
    inputs:
      artifact:
        required: false
        type: string
      name:
        required: false
        type: string

jobs:
  gh-release:
    name: download, release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        if: ${{ inputs.artifact != '' }}
        with:
          pattern: ${{ inputs.artifact }}
          path: artifact/
          merge-multiple: true

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: artifact/*
          tag_name: ${{ inputs.name }}
          fail_on_unmatched_files: false
          generate_release_notes: true
