name: "[reusable] lint-clang"

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: "19"

jobs:
  lint-clang:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check code with clang-format
        uses: jidicula/clang-format-action@v4.14.0
        with:
          clang-format-version: ${{ inputs.version }}
