name: "[reusable] publish-npm"

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      node-version:
        required: false
        type: string
        default: "16"

jobs:
  publish-npm:
    name: install & publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install project
        run: npm ci
      - name: Publish NPM package
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
