name: "[reusable] test-node"

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
      node-version:
        required: false
        type: string
        default: "16"
      task-test:
        required: false
        type: string
        default: test

jobs:
  test-node:
    name: test
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install project
        run: |
          npm ci
      - name: Run tests
        run: |
          npm run ${{ inputs.task-test }}
